// Supabase SQL Migration Script string for admin copy-paste
export const SUPABASE_AI_PROMPTS_SQL = [
  '-- ==============================================================================',
  '-- AI PROMPTS SCHEMA & SEED FOR ROSEOIL.IN',
  '-- Table: ai_prompts',
  '-- Description: Stores AI prompts, system instructions, variables, and parameters',
  '-- Store ID: essential_oils_perfumes_store_01',
  '-- ==============================================================================',
  '',
  '-- Drop existing table if store_id was previously created as UUID',
  'DROP TABLE IF EXISTS public.ai_prompts CASCADE;',
  '',
  'CREATE TABLE IF NOT EXISTS public.ai_prompts (',
  '  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),',
  "  store_id VARCHAR(100) NOT NULL DEFAULT 'essential_oils_perfumes_store_01',",
  '  slug VARCHAR(100) NOT NULL,',
  '  title VARCHAR(255) NOT NULL,',
  '  description TEXT,',
  "  category VARCHAR(100) NOT NULL DEFAULT 'Catalog & SEO',",
  '  system_prompt TEXT NOT NULL,',
  '  user_prompt_template TEXT NOT NULL,',
  "  variables JSONB NOT NULL DEFAULT '[]'::jsonb,",
  "  model VARCHAR(100) NOT NULL DEFAULT 'gemini-1.5-flash',",
  '  temperature NUMERIC(3,2) NOT NULL DEFAULT 0.70,',
  '  max_output_tokens INTEGER NOT NULL DEFAULT 3500,',
  "  expected_output_format VARCHAR(50) NOT NULL DEFAULT 'json',",
  '  is_active BOOLEAN NOT NULL DEFAULT true,',
  "  sample_input JSONB NOT NULL DEFAULT '{}'::jsonb,",
  '  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),',
  '  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),',
  '  CONSTRAINT ai_prompts_store_slug_unique UNIQUE (store_id, slug)',
  ');',
  '',
  '-- Indexes for fast lookup',
  'CREATE INDEX IF NOT EXISTS idx_ai_prompts_store_slug ON public.ai_prompts(store_id, slug);',
  'CREATE INDEX IF NOT EXISTS idx_ai_prompts_category ON public.ai_prompts(category);',
  '',
  '-- Enable Row Level Security (RLS)',
  'ALTER TABLE public.ai_prompts ENABLE ROW LEVEL SECURITY;',
  '',
  '-- Allow select for all',
  'DROP POLICY IF EXISTS "Allow select for all on ai_prompts" ON public.ai_prompts;',
  'CREATE POLICY "Allow select for all on ai_prompts" ON public.ai_prompts',
  '  FOR SELECT USING (true);',
  '',
  '-- Allow full access for service_role, anon, and authenticated users',
  'DROP POLICY IF EXISTS "Allow all for authenticated/service on ai_prompts" ON public.ai_prompts;',
  'CREATE POLICY "Allow all for authenticated/service on ai_prompts" ON public.ai_prompts',
  '  FOR ALL USING (true) WITH CHECK (true);',
  '',
  '-- Trigger for auto-updating updated_at',
  'CREATE OR REPLACE FUNCTION public.handle_ai_prompts_updated_at()',
  'RETURNS TRIGGER AS $func$',
  'BEGIN',
  '  NEW.updated_at = now();',
  '  RETURN NEW;',
  'END;',
  '$func$ LANGUAGE plpgsql;',
  '',
  'DROP TRIGGER IF EXISTS trigger_ai_prompts_updated_at ON public.ai_prompts;',
  'CREATE TRIGGER trigger_ai_prompts_updated_at',
  '  BEFORE UPDATE ON public.ai_prompts',
  '  FOR EACH ROW',
  '  EXECUTE FUNCTION public.handle_ai_prompts_updated_at();',
  '',
  '-- ==============================================================================',
  '-- SEED DEFAULT AI PROMPTS FOR ROSEOIL.IN',
  '-- ==============================================================================',
  '',
  'INSERT INTO public.ai_prompts (',
  '  store_id,',
  '  slug,',
  '  title,',
  '  description,',
  '  category,',
  '  system_prompt,',
  '  user_prompt_template,',
  '  variables,',
  '  model,',
  '  temperature,',
  '  max_output_tokens,',
  '  expected_output_format,',
  '  sample_input',
  ') VALUES',
  '',
  '-- 1. All-in-One SEO & Product Description Architect',
  '(',
  "  'essential_oils_perfumes_store_01',",
  "  'all_in_one_seo_and_description',",
  "  'All-In-One SEO & Product Description Architect',",
  "  'Generates complete high-converting product copy: SEO Meta Title, Meta Description, Search Keywords, 350-word story, and 3-tier Olfactory Pyramid (top, heart, base).',",
  "  'Catalog & SEO',",
  '  $str$You are an internationally respected Essential Oil Chemist, Botanical Analyst, and Chief SEO Strategist for RoseOil.in, a pure essential oils company.',
  '',
  'Generate precise, evocative, and high-converting copy grounded in real botanical and aromatherapeutic facts. Do NOT use boilerplate templates, robotic keyword stuffing, or generic macro phrasing. Tailor every word to the specific plant source, extraction method, chemical character, and therapeutic use of the product.$str$,',
  '  $str$DEEP ANALYSIS & BESPOKE CREATION FOR: "{{prompt}}"',
  '',
  'Context:',
  '- Product Name: "{{prompt}}"',
  '- Category Context: {{category}}',
  '',
  'INSTRUCTIONS FOR COPYWRITER & SEO ARCHITECT:',
  '1. Deep Botanical Analysis: Analyze the core essence of "{{prompt}}". Is it a relaxation/sleep-support oil, cognitive-focus oil, skincare carrier oil, therapeutic root/rhizome extract, uplifting citrus, or deep woody/resinous oil?',
  '2. High-Value SEO Metadata:',
  '   - "meta_title": (Strictly 50-60 characters). High-CTR title tag tailored specifically to "{{prompt}}". Must be natural and never use repetitive macro templates.',
  '   - "meta_description": (Strictly 140-155 characters). High-conversion Google search snippet highlighting unique botanical benefits of the product.',
  '   - "meta_keywords": (12-16 high-value search queries). Target buyer-intent terms specific to "{{prompt}}" (e.g. therapeutic properties, aromatherapy uses, extraction method, purity grade).',
  '3. Product Description (300-350 words in 3-4 rich, sensory paragraphs):',
  '   - Paragraph 1: Scent character, plant origin, and harvesting/sourcing context.',
  '   - Paragraph 2: Aromatic evolution (top notes opening into a harmonious heart and deep drydown).',
  '   - Paragraph 3: Purity, extraction method, and quality standards (e.g. steam-distilled, cold-pressed, GC-MS tested).',
  '   - Paragraph 4: Practical application (diffusion, topical dilution with a carrier oil, aromatherapy blending).',
  '4. Olfactory Pyramid:',
  '   - "top": Array of 3 precise opening notes.',
  '   - "heart": Array of 3 nuanced heart notes.',
  '   - "base": Array of 3 grounding drydown notes.',
  '',
  'RETURN STRICTLY A VALID JSON OBJECT with NO markdown, NO preambles:',
  '{',
  '  "meta_title": "...",',
  '  "meta_description": "...",',
  '  "meta_keywords": "...",',
  '  "description": "...",',
  '  "scent_notes": {',
  '    "top": ["...", "...", "..."],',
  '    "heart": ["...", "...", "..."],',
  '    "base": ["...", "...", "..."]',
  '  }',
  '}$str$,',
  '  $str$[',
  '    {"name": "prompt", "label": "Product Name", "description": "Name of the essential oil or botanical distillate", "required": true},',
  '    {"name": "category", "label": "Category Context", "description": "Category or aroma family", "required": false}',
  '  ]$str$::jsonb,',
  "  'gemini-1.5-flash',",
  '  0.70,',
  '  3500,',
  "  'json',",
  '  $str${"prompt": "Pure Bulgarian Rose Otto Oil", "category": "Floral Essential Oils"}$str$::jsonb',
  '),',
  '',
  '-- 2. Dedicated Product Description',
  '(',
  "  'essential_oils_perfumes_store_01',",
  "  'product_description',",
  "  'Product Story & Description',",
  "  'Writes an evocative 250-word product description emphasizing purity, extraction method, and wellness benefits.',",
  "  'Catalog & SEO',",
  '  $str$You are a premier Essential Oils Copywriter for RoseOil.in. Your writing is precise, sensorially rich, and converts discerning aromatherapy and wellness buyers.$str$,',
  '  $str$Write a bespoke, 250-word product description for "{{prompt}}". Emphasize its 100% pure botanical extraction, therapeutic-grade purity, unique scent notes, and long-lasting aroma.$str$,',
  '  $str$[',
  '    {"name": "prompt", "label": "Product Name", "description": "The product to describe", "required": true}',
  '  ]$str$::jsonb,',
  "  'gemini-1.5-flash',",
  '  0.70,',
  '  1000,',
  "  'text',",
  '  $str${"prompt": "Steam-Distilled Sandalwood Essential Oil"}$str$::jsonb',
  '),',
  '',
  '-- 3. Scent Notes & Olfactory Pyramid Extractor',
  '(',
  "  'essential_oils_perfumes_store_01',",
  "  'scent_notes',",
  "  'Olfactory Pyramid & Note Extractor',",
  "  'Analyzes a fragrance profile and outputs a structured 3-tier pyramid (Top Notes, Heart Notes, Base Notes) in clean JSON.',",
  "  'Catalog & SEO',",
  '  $str$You are a trained Aroma Analyst and Olfactory Specialist at RoseOil.in.$str$,',
  '  $str$Analyze the fragrance profile of "{{prompt}}". Return ONLY a valid JSON object with {"top": ["...","...","..."], "heart": ["...","...","..."], "base": ["...","...","..."]}.$str$,',
  '  $str$[',
  '    {"name": "prompt", "label": "Essential Oil Name", "description": "Name of the essential oil or blend", "required": true}',
  '  ]$str$::jsonb,',
  "  'gemini-1.5-flash',",
  '  0.50,',
  '  800,',
  "  'json',",
  '  $str${"prompt": "Frankincense Essential Oil"}$str$::jsonb',
  '),',
  '',
  '-- 4. SEO Metadata & Keyword Strategist',
  '(',
  "  'essential_oils_perfumes_store_01',",
  "  'seo_metadata',",
  "  'SEO Metadata & Buyer-Intent Keywords',",
  "  'Performs high-CTR Google search metadata research and returns meta_title (50-60 chars), meta_keywords, and meta_description.',",
  "  'Catalog & SEO',",
  '  $str$You are an executive E-Commerce SEO Specialist specializing in essential oils and natural wellness brands at RoseOil.in.$str$,',
  '  $str$Perform deep SEO market research for "{{prompt}}". Return ONLY valid JSON: {"meta_title": "...", "meta_keywords": "...", "meta_description": "..."}.$str$,',
  '  $str$[',
  '    {"name": "prompt", "label": "Product / Page Topic", "description": "Target keyword or product name", "required": true}',
  '  ]$str$::jsonb,',
  "  'gemini-1.5-flash',",
  '  0.60,',
  '  800,',
  "  'json',",
  '  $str${"prompt": "Organic Lavender Essential Oil"}$str$::jsonb',
  '),',
  '',
  '-- 5. Authentic Verified Customer Reviews Generator',
  '(',
  "  'essential_oils_perfumes_store_01',",
  "  'customer_reviews',",
  "  'Authentic Customer Reviews & Social Proof',",
  "  'Generates 3 nuanced, highly realistic 5-star customer reviews tailored to the product scent notes and longevity.',",
  "  'Community & Social Proof',",
  '  $str$You are a customer voice specialist creating authentic, credible, high-trust essential oil reviews reflecting real buyer experiences for RoseOil.in.$str$,',
  '  $str$Return ONLY a valid JSON array of 3 authentic, 5-star customer reviews specifically for "{{prompt}}".',
  'JSON format:',
  '[',
  '  {',
  '    "name": "Customer Name",',
  '    "rating": 5,',
  '    "verified": true,',
  '    "date": "2 days ago",',
  '    "title": "Review Title",',
  '    "review": "Detailed review praising notes, purity, and effectiveness."',
  '  }',
  ']$str$,',
  '  $str$[',
  '    {"name": "prompt", "label": "Product Name", "description": "Product for review generation", "required": true}',
  '  ]$str$::jsonb,',
  "  'gemini-1.5-flash',",
  '  0.75,',
  '  1500,',
  "  'json',",
  '  $str${"prompt": "Wild Himalayan Cedarwood Essential Oil"}$str$::jsonb',
  '),',
  '',
  '-- 6. Category SEO Description',
  '(',
  "  'essential_oils_perfumes_store_01',",
  "  'category_description',",
  "  'Product Category Description',",
  "  'Writes a rich 100-word SEO category description highlighting sourcing standards and 100% pure, undiluted quality.',",
  "  'Catalog & SEO',",
  '  $str$You are a natural products brand copywriter for RoseOil.in.$str$,',
  '  $str$Write a rich, poetic 100-word SEO category description for "{{prompt}}". Highlight sourcing standards, extraction quality, and 100% pure, undiluted botanical purity.$str$,',
  '  $str$[',
  '    {"name": "prompt", "label": "Category Name", "description": "Name of the collection or category", "required": true}',
  '  ]$str$::jsonb,',
  "  'gemini-1.5-flash',",
  '  0.70,',
  '  600,',
  "  'text',",
  '  $str${"prompt": "Pure Organic Essential Oils"}$str$::jsonb',
  '),',
  '',
  '-- 7. AI Wellness Concierge & Chatbot',
  '(',
  "  'essential_oils_perfumes_store_01',",
  "  'chatbot',",
  "  'AI Wellness Concierge & Scent Advisor',",
  "  'Powers the real-time customer concierge assistant, recommending essential oils, addressing questions, and guiding customers with clarity and warmth.',",
  "  'AI Shopping Experience',",
  '  $str$You are the AI Wellness Concierge for RoseOil.in, a pure essential oils company.',
  'You speak with warmth, clarity, and deep knowledge of natural essential oil extraction, purity standards, and aromatherapy wellness.',
  'Keep answers concise (2-4 sentences), friendly, and helpful. Always invite the patron to explore our pure, undiluted essential oils.$str$,',
  '  $str$User Message: "{{prompt}}"',
  '',
  'Context / Store Data:',
  '{{context}}',
  '',
  'Provide a warm, concise response answering the customer query accurately.$str$,',
  '  $str$[',
  '    {"name": "prompt", "label": "User Message", "description": "The message sent by the customer", "required": true},',
  '    {"name": "context", "label": "Store Knowledge / Products Context", "description": "Catalog data or order info", "required": false}',
  '  ]$str$::jsonb,',
  "  'gemini-1.5-flash',",
  '  0.70,',
  '  1000,',
  "  'text',",
  '  $str${"prompt": "Which essential oil is best for evening relaxation and better sleep?", "context": "Products: French Lavender Essential Oil, Bulgarian Rose Otto Oil, Mysore Sandalwood Essential Oil"}$str$::jsonb',
  '),',
  '',
  '-- 8. Scent Memory & Olfactory Recommendation Finder',
  '(',
  "  'essential_oils_perfumes_store_01',",
  "  'scent_memory_finder',",
  "  'Scent Memory Olfactory Recommendation Engine',",
  "  'Interprets emotional memories, nostalgic places, or personal feelings to recommend matching essential oils with olfactory rationale.',",
  "  'AI Shopping Experience',",
  '  $str$You are the Scent Memory Advisor for RoseOil.in. You translate personal memories, moods, and sensory nostalgic moments into matching essential oil recommendations from our pure botanical collection.$str$,',
  '  $str$The customer describes their cherished memory: "{{prompt}}"',
  '',
  'Recommend the ideal essential oil profile and return ONLY a valid JSON object:',
  '{',
  '  "recommended_scent_type": "...",',
  '  "evocative_title": "...",',
  '  "poetic_rationale": "...",',
  '  "primary_notes": ["...", "...", "..."],',
  '  "matching_product_family": "..."',
  '}$str$,',
  '  $str$[',
  '    {"name": "prompt", "label": "Memory Description", "description": "User memory or emotional sensation", "required": true}',
  '  ]$str$::jsonb,',
  "  'gemini-1.5-flash',",
  '  0.75,',
  '  1200,',
  "  'json',",
  '  $str${"prompt": "A warm monsoon evening walking on wet earthen soil after the first rain"}$str$::jsonb',
  '),',
  '',
  '-- 9. Editorial Essential Oils & Wellness Blog Generator',
  '(',
  "  'essential_oils_perfumes_store_01',",
  "  'blog_post',",
  "  'Editorial Essential Oils & Wellness Blog Generator',",
  "  'Generates a comprehensive 600-word editorial article for journal publications, SEO authority, and customer education.',",
  "  'Editorial & Content',",
  '  $str$You are the Editor-in-Chief of the RoseOil.in Botanical Journal, covering essential oil science, extraction methods, and aromatherapy wellness.$str$,',
  '  $str$Write an engaging, SEO-optimized 600-word editorial journal article on "{{prompt}}".',
  'Structure with:',
  '1. Compelling Headline & Subhead',
  '2. Botanical Source & Extraction Method',
  '3. Scent Chemistry & Therapeutic Benefits',
  '4. Practical Usage & Blending Guide',
  '',
  'Return formatted in clean Markdown.$str$,',
  '  $str$[',
  '    {"name": "prompt", "label": "Article Topic", "description": "Blog topic or botanical subject", "required": true}',
  '  ]$str$::jsonb,',
  "  'gemini-1.5-flash',",
  '  0.70,',
  '  2500,',
  "  'markdown',",
  '  $str${"prompt": "Steam Distillation vs. Cold Pressing: How Extraction Method Shapes an Essential Oil Character"}$str$::jsonb',
  '),',
  '',
  '-- 10. Product Q&A & Scent Advisory Response',
  '(',
  "  'essential_oils_perfumes_store_01',",
  "  'qa_answer',",
  "  'Customer Q&A & Advisory Responder',",
  "  'Answers technical product questions (potency, purity, skin sensitivity, usage) with authority and clarity.',",
  "  'Community & Social Proof',",
  '  $str$You are a Senior Essential Oils Advisor and Formulator at RoseOil.in answering customer inquiries with precision and clarity.$str$,',
  '  $str$Customer Question regarding "{{prompt}}": "{{context}}"',
  '',
  'Provide a refined, factually accurate answer explaining our extraction method, purity testing, skin safety, and application guidance.$str$,',
  '  $str$[',
  '    {"name": "prompt", "label": "Product Name", "description": "The product being inquired about", "required": true},',
  '    {"name": "context", "label": "Customer Question", "description": "The specific question asked", "required": true}',
  '  ]$str$::jsonb,',
  "  'gemini-1.5-flash',",
  '  0.60,',
  '  800,',
  "  'text',",
  '  $str${"prompt": "Bulgarian Rose Otto Oil", "context": "Is this oil safe to apply directly onto sensitive skin without a carrier oil?"}$str$::jsonb',
  '),',
  '',
  '-- 11. Botanical Ingredients Formulation & INCI',
  '(',
  "  'essential_oils_perfumes_store_01',",
  "  'ingredients',",
  "  'Botanical Ingredients Formulation & INCI',",
  "  'Analyzes the botanical product and generates an accurate, pure botanical ingredients / INCI list.',",
  "  'Catalog & SEO',",
  '  $str$You are a Senior Cosmetic Chemist and Botanical Formulator for RoseOil.in.$str$,',
  '  $str$Analyze the botanical product "{{prompt}}". Return ONLY a comma-separated list of 3-5 authentic, pure botanical ingredients (e.g. "Pure Hydro-Distilled Rosa Damascena Extract, Santalum Album (Sandalwood) Oil, Simmondsia Chinensis (Jojoba) Oil"). No quotes, no markdown.$str$,',
  '  $str$[',
  '    {"name": "prompt", "label": "Product Name", "description": "The botanical product to analyze", "required": true}',
  '  ]$str$::jsonb,',
  "  'gemini-1.5-flash',",
  '  0.50,',
  '  500,',
  "  'text',",
  '  $str${"prompt": "Pure Bulgarian Rose Otto Oil"}$str$::jsonb',
  ')',
  '',
  'ON CONFLICT (store_id, slug) DO UPDATE SET',
  '  title = EXCLUDED.title,',
  '  description = EXCLUDED.description,',
  '  category = EXCLUDED.category,',
  '  system_prompt = EXCLUDED.system_prompt,',
  '  user_prompt_template = EXCLUDED.user_prompt_template,',
  '  variables = EXCLUDED.variables,',
  '  model = EXCLUDED.model,',
  '  temperature = EXCLUDED.temperature,',
  '  max_output_tokens = EXCLUDED.max_output_tokens,',
  '  expected_output_format = EXCLUDED.expected_output_format,',
  '  sample_input = EXCLUDED.sample_input,',
  '  updated_at = now();',
].join('\n');
